### ISSUE TITLE
Exception: AtomicBuffer is not correctly aligned 

### ISSUE THREAD

**Issue by appreciated** [tkowalcz/tjahzi#122]
We are hitting this issue on every startup.

I think this might be related with us using a x86 JVM with Java 17.

### Stacktrace
```java
ERROR StatusConsoleListener Could not create plugin of type class pl.tkowalcz.tjahzi.log4j2.LokiAppender for element Loki: java.lang.IllegalStateException: AtomicBuffer is not correctly aligned: addressOffset=12 is not divisible by 8
 java.lang.IllegalStateException: AtomicBuffer is not correctly aligned: addressOffset=12 is not divisible by 8
	at org.agrona.concurrent.UnsafeBuffer.verifyAlignment(UnsafeBuffer.java:388)
	at org.agrona.concurrent.errors.DistinctErrorLog.<init>(DistinctErrorLog.java:124)
	at org.agrona.concurrent.errors.DistinctErrorLog.<init>(DistinctErrorLog.java:112)
	at pl.tkowalcz.tjahzi.stats.StandardMonitoringModule.<init>(StandardMonitoringModule.java:33)
	at pl.tkowalcz.tjahzi.log4j2.LokiAppenderBuilder.build(LokiAppenderBuilder.java:125)
	at pl.tkowalcz.tjahzi.log4j2.LokiAppenderBuilder.build(LokiAppenderBuilder.java:30)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1075)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:679)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:264)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:227)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:183)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:69)
	at d.p.o.core.utils.LokiAppenderUtils.initLokiAppender(LokiAppenderUtils.java:72)
	at d.p.o.core.utils.LoggingUtils.configureLogger(LoggingUtils.java:68)
	at d.p.o.localRunner.Start.configureLogger(Start.java:113)
	at d.p.o.localRunner.Start.main(Start.java:35)
ERROR StatusConsoleListener Unable to invoke factory method in class pl.tkowalcz.tjahzi.log4j2.LokiAppender for element Loki: java.lang.IllegalStateException: No factory method found for class pl.tkowalcz.tjahzi.log4j2.LokiAppender
 java.lang.IllegalStateException: No factory method found for class pl.tkowalcz.tjahzi.log4j2.LokiAppender
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:268)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:140)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1075)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:679)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:264)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:227)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:183)
	at org.apache.logging.log4j.core.config.builder.impl.DefaultConfigurationBuilder.build(DefaultConfigurationBuilder.java:69)
	at d.p.o.core.utils.LokiAppenderUtils.initLokiAppender(LokiAppenderUtils.java:72)
	at d.p.o.core.utils.LoggingUtils.configureLogger(LoggingUtils.java:68)
	at d.p.o.localRunner.Start.configureLogger(Start.java:113)
	at d.p.o.localRunner.Start.main(Start.java:35)
```

#### StandardMonitoringModule
![grafik](https://github.com/tkowalcz/tjahzi/assets/1729845/32eb3ce7-5078-4360-8e7d-93b2e372d042)
#### UnsafeBuffer
![grafik](https://github.com/tkowalcz/tjahzi/assets/1729845/d4d52144-1f93-49b6-a4cc-1781f9c404ce)
![grafik](https://github.com/tkowalcz/tjahzi/assets/1729845/346582e4-63ba-4247-b81b-f01e3bd8e0ac)

**Comment by appreciated** [comment]
@tkowalcz Thank you so much! This is the one:
https://adoptium.net/de/temurin/releases/?version=17&package=jdk&arch=x86

**Comment by appreciated** [comment]
You should be able to fix this issue by replacing the attribute `StandardMonitoringModule.ERROR_LOG_CAPACITY` with the following code:
```
int ERROR_LOG_CAPACITY = UNSAFE.arrayBaseOffset(byte[].class) * 64;
```

This would result on 64-Bit Systems in the current value of 1024, on 32-Bit systems in 768 which should both work with the `UnsafeBuffer`. 
Not sure if this contradicts with other actual requirements you have with the `UnsafeBuffer`.

**Comment by appreciated** [comment]
Fixed by upgrading to new Version:
```
<dependency>
    <groupId>pl.tkowalcz.tjahzi</groupId>
    <artifactId>log4j2-appender</artifactId>
    <version>0.9.32</version>
</dependency>
```

**Comment by tkowalcz** [comment]
Ha! Didn't think of that :) I know I fixed similar error but thought this is yet another x86 issue. Glad you worked it out.
