### ISSUE TITLE
How to use the log4j-appender with property files and labels

### ISSUE THREAD

**Issue by rmetzger** [tkowalcz/tjahzi#72]
My existing project is configured in the properties format of log4j2 already. I would like to introduce the loki appender, but I'm failing to add the labels.

This is my current properties file:
```
monitorInterval=30

rootLogger.level = INFO
rootLogger.appenderRef.file.ref = FileAppender
rootLogger.appenderRef.loki.ref = loki-appender

appender.loki.name = loki-appender
appender.loki.type = Loki
appender.loki.host = loki
appender.loki.port = 3100
appender.loki.layout.type = PatternLayout
appender.loki.layout.pattern = %X{tid} [%t] %d{MM-dd HH:mm:ss.SSS} %5p %c{1} - %m%n%exception{full}
appender.loki.label.source.type = label
appender.loki.label.source.name = source
appender.loki.label.source.value = log4j
```

And this is the error I'm facing:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: org.apache.logging.log4j.core.config.ConfigurationException: No type attribute provided for component label
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.createComponent(PropertiesConfigurationBuilder.java:334)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.processRemainingProperties(PropertiesConfigurationBuilder.java:348)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.createAppender(PropertiesConfigurationBuilder.java:225)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.build(PropertiesConfigurationBuilder.java:158)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:56)
	at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:35)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:458)
	at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:385)
	at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:293)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:647)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:668)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:329)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
	at org.apache.flink.client.cli.CliFrontend.<clinit>(CliFrontend.java:89)
root@ubuntu:/flink-1.13.2#
```

**Comment by rmetzger** [comment]
Experimenting further with 
```
packages="pl.tkowalcz.tjahzi.log4j2"

# Allows this configuration to be modified at runtime. The file will be checked every 30 seconds.
monitorInterval=30

rootLogger.level = INFO
rootLogger.appenderRef.file.ref = FileAppender
rootLogger.appenderRef.loki.ref = loki-appender

appender.loki.name = loki-appender
appender.loki.type = Loki
appender.loki.host = loki
appender.loki.port = 3100
appender.loki.layout.type = PatternLayout
appender.loki.layout.pattern = %X{tid} [%t] %d{MM-dd HH:mm:ss.SSS} %5p %c{1} - %m%n%exception{full}
#appender.loki.labels.type = KeyValuePair
appender.loki.labels.type = labels
appender.loki.labels.name = source
appender.loki.labels.value = log4j
```

but still no luck: 
```
ERROR StatusLogger Unable to locate plugin for labels
DEBUG StatusLogger Building Plugin[name=appender, class=pl.tkowalcz.tjahzi.log4j2.LokiAppender].
ERROR StatusLogger Could not create plugin of type class pl.tkowalcz.tjahzi.log4j2.LokiAppender for element Loki: java.lang.NullPointerException
 java.lang.NullPointerException
	at org.apache.logging.log4j.core.config.plugins.visitors.PluginElementVisitor.visit(PluginElementVisitor.java:52)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.injectFields(PluginBuilder.java:185)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:121)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:579)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:651)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:668)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:329)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:349)
	at org.apache.flink.client.cli.CliFrontend.<clinit>(CliFrontend.java:89)
```

**Comment by tkowalcz** [comment]
Hi,

I never tried configuring Loki with properties. I will have time later this evening and will look into this. If it works I’ll add it to documentation.

**Comment by rmetzger** [comment]
Awesome, thanks a lot!

**Comment by tkowalcz** [comment]
So far I was able to configure Tjahzi this way:

```properties
appender.loki.header.type = header
appender.loki.header.name = server
appender.loki.header.value = 127.0.0.1

appender.loki.label.type = label
appender.loki.label.name = source
appender.loki.label.value = log4j
```

I did not found a way to specify multiple labels. I will keep trying.

**Comment by tkowalcz** [comment]
I figured it out. This is the relevant part of the config:

```properties
appender.loki.labels[0].type=label
appender.loki.labels[0].name=server
appender.loki.labels[0].value=127.0.0.1

appender.loki.labels[1].type=label
appender.loki.labels[1].name=source
appender.loki.labels[1].value=log4j
```

Here's [test](https://github.com/tkowalcz/tjahzi/blob/e073d52d53e5d50e8c1aa15df8d97af2451267a5/log4j2-appender/src/test/java/pl/tkowalcz/tjahzi/log4j2/LokiPropertiesFileTest.java) and [config](https://github.com/tkowalcz/tjahzi/blob/e073d52d53e5d50e8c1aa15df8d97af2451267a5/log4j2-appender/src/test/resources/appender-test-with-log-label-set.properties).

Please let me know if that solves your problem.

**Comment by rmetzger** [comment]
Sorry for not reacting. I didn't see the second comment with the multiple labels!
Thanks a lot for figuring this out! Now it seems so obvious ;) I'll report back in case I have other issues!
