### ISSUE TITLE
TjahziInitializer causing Out of Memory Error, when running in Docker Container

### ISSUE THREAD

**Issue by akhilvpsharma** [tkowalcz/tjahzi#80]
When running project in Docker Container, following are the error logs:
```
Setting Active Processor Count to 8
Calculating JVM memory based on 18761956K available memory
Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M -Xmx18103971K -XX:MaxMetaspaceSize=145984K -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: 18761956K, Thread Count: 250, Loaded Class Count: 23360, Headroom: 0%)
Enabling Java Native Memory Tracking
Adding 128 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -XX:+ExitOnOutOfMemoryError -XX:ActiveProcessorCount=8 -XX:MaxDirectMemorySize=10M -Xmx18103971K -XX:MaxMetaspaceSize=145984K -XX:ReservedCodeCacheSize=240M -Xss1M -XX:+UnlockDiagnosticVMOptions -XX:NativeMemoryTracking=summary -XX:+PrintNMTStatistics -Dorg.springframework.cloud.bindings.boot.enable=true
[
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at pl.tkowalcz.tjahzi.TjahziInitializer.allocateJavaBuffer(TjahziInitializer.java:97)
	at pl.tkowalcz.tjahzi.TjahziInitializer.createLoggingSystem(TjahziInitializer.java:29)
	at pl.tkowalcz.tjahzi.log4j2.LokiAppenderBuilder.build(LokiAppenderBuilder.java:137)
	at pl.tkowalcz.tjahzi.log4j2.LokiAppenderBuilder.build(LokiAppenderBuilder.java:31)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
	at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)
	at com.sara.extractservice.ExtractServiceApplication.main(ExtractServiceApplication.java:36)
	... 8 more
```
I am using Ubuntu 20.04.2 LTS, with 32 GB RAM. The Docker Image was created using `mvn spring-boot:build-image`. Could you share what changes I need to make for fixing this issue? Thanks.

**Comment by tkowalcz** [comment]
Hi,

I am not very versed in Docker usage, but according to your output I think this is what happens:

- You have 18761956K (~18GB) of available memory. 
- JVM old gen will take 18103971K (17,2GB) out of it.
- Metaspace and code cache will take ~382MB
- Thread stacks (`-Xss1M`) will take 250MB (`Thread Count: 250` * 1M)

If I am correct this totals to 18751715K so the container has about 10MB of free memory.
This lines up nicely with `-XX:MaxDirectMemorySize=10M` setting that allows the java app to allocate at most 10M of
off-heap data.

To fix this you need to increase `MaxDirectMemorySize` while decreasing other settings OR set Tjahzi to allocate less than 10M of off-heap data.

Let me elaborate on that last option. While configuring Tjahzi you can set `useOffHeapBuffer=false` so that data structures used by Tjahzi will be part of a regular Java heap. I do not expect that this would have significant performance impact on the application.

You can also set `bufferSizeMegabytes` to value lower than 10M from its default value of 32M. This can impact log delivery if Tjahzi cannot keep up sending data to Loki while application produices the logs into the buffer.

**Comment by tkowalcz** [comment]
Hi,

I am not very versed in Docker usage, but according to your output I think this is what happens:

- You have 18761956K (~18GB) of available memory. 
- JVM old gen will take 18103971K (17,2GB) out of it.
- Metaspace and code cache will take ~382MB
- Thread stacks (`-Xss1M`) will take 250MB (`Thread Count: 250` * 1M)

If I am correct this totals to 18751715K so the container has about 10MB of free memory.
This lines up nicely with `-XX:MaxDirectMemorySize=10M` setting that allows the java app to allocate at most 10M of
off-heap data.

To fix this you need to increase `MaxDirectMemorySize` while decreasing other settings OR set Tjahzi to allocate less than 10M of off-heap data.

Let me elaborate on that last option. While configuring Tjahzi you can set `useOffHeapBuffer=false` so that data structures used by Tjahzi will be part of a regular Java heap. I do not expect that this would have significant performance impact on the application.

You can also set `bufferSizeMegabytes` to value lower than 10M from its default value of 32M. This can impact log delivery if Tjahzi cannot keep up sending data to Loki while application produices the logs into the buffer.

**Comment by tkowalcz** [comment]
@akhilvpsharma doe this explanation help and fixes the issue or do you need any more assistance?

**Comment by akhilvpsharma** [comment]
@tkowalcz Thanks a lot for the explanation. Sorry for the late reply, took a while to test. It's working as expected now. Closing the ticket. Thanks again :)
